### ISSUE TITLE
TCGETS2 is not available on all arches

### ISSUE THREAD

**Issue by QuLogic** [bugst/go-serial#112]
You can check the `zerrors_linux_*.go` files in https://github.com/golang/sys/tree/master/unix for `TCGETS2`, which is missing from a few of the files.

I also found [this message from glibc](https://sourceware.org/legacy-ml/libc-alpha/2019-04/msg00200.html) about how it's architecture specific, though I did not find any specific docs about it.

Specifically, it is `ppc64le` that is failing when I [build on Fedora](https://koji.fedoraproject.org/koji/taskinfo?taskID=71690235).

**Comment by cmaglie** [comment]
That's a bummer, I guess we should split `func (port *unixPort) setSpecialBaudrate(speed uint32) error` by architecture and put an "unimplemented" placeholder for `ppc64le` (unless you have a different solution for that architecture).

**Comment by QuLogic** [comment]
Unfortunately, I do not have any other solution. It's a primary build target in Fedora, but I'm not even sure if anyone uses it with go-serial. If they do, hopefully they can come around with a better fix if one exists.
