### ISSUE TITLE
Read() Doesn't Ignore Newline (String Formatted not Correctly)

### ISSUE THREAD

**Issue by KiddoV** [bugst/go-serial#133]
I have a programmed serial device. It will output the response whenever I ``Write()`` to the COM port.
For example, with [TeraTerm](https://ttssh2.osdn.jp/index.html.en), when I write ``at`` as a command, the device should print out:
```txt
at

OK
```
... Which is the format that I wanted be. (100% every time)

However when reading with:
```go
// Read COM port
buff := make([]byte, 1000)
for {
	n, err := port.Read(buff)
	if err != nil {
		//handle error...
	}
	if n == 0 {
		break
	}
	fmt.Print(string(buff[:n]))
}
```
The output is not consistent, and not formatted correctly (sometime correct though)
```txt
a
t

OK
__________
t
a

OK
__________
at


OK
...
```
The order of ``buff[:n]`` (before it convert to string) in the ``for loop`` is:
_Also not consistent, sometime it would put the ``[97]`` (97 is letter ``a``) later on_
```txt
[97]
[116 13 13 10]
[13 10 79 75 13 10]
[13]
[13 10]
```
My Questions:
- So clearly that it all reading the same serial port, but why is ``TeraTerm`` can handle it correctly every time, and how do I correct this issue in ``Go``? (I already set the config MODE the same on every platform ``&serial.Mode{BaudRate: 115200, Parity:   serial.NoParity, DataBits: 8, StopBits: serial.OneStopBit}``)

- Can I make the ``buffer`` to ignore when seeing the ``\n (newline)`` character? Because in the device, it would out put the ``13`` ASCII code which is the ``newline`` character when convert it to string anyway. So I don't need to wait for the ``\n``.

Thanks!

**Comment by cmaglie** [comment]
The fact that `Read` returns a partial line is normal (it depends on what data is arrived in the serial read buffer at the moment Read is called), but there should be no extra `\n` or out-of-order bytes.

Could you paste the full source code (or even better a minimal example that reproduces the issue)?

**Comment by KiddoV** [comment]
@cmaglie Thanks for the reply. I guess that is depend on the device. I just used the simple code that you provided in the docs, it is nothing special.
```go
/*
defaultSerialMode := &serial.Mode{
	BaudRate: 115200,
	Parity:   serial.NoParity,
	DataBits: 8,
	StopBits: serial.OneStopBit,
}
*/
_, err := thisPort.Write([]byte(writeMsg + "\n\r"))
if err != nil {
	//Handle error
}
// Read COM port
buff := make([]byte, 1000)
for {
	n, err := thisPort.Read(buff)
	if err != nil {
		a.LogError("Error reading COM!! " + err.Error())
	}
	if n == 0 {
                //This line is never execute, on my device
		break
	}
	fmt.Print(buff[:n], "\n")
}
```
I am just curious of how TeraTerm can make it look good every time. The fact that they both reading the same COM port and the same device. Maybe TeraTerm has some special handler for string conversion? IDK

**Comment by cmaglie** [comment]
well It's not exactly the same, this line:

```
	fmt.Print(buff[:n], "\n")
```

prints an extra newline for each "chunk" of data that is received, if you change it to:

```
	fmt.Print(string(buff[:n]))
```

it should already improve things.
Looking at your previous dump:

```
[97]                  <- "a"
[116 13 13 10]        <- "t\r\r\n"
[13 10 79 75 13 10]   <- "\r\nOK\r\n"
[13]                  <- "\r"
[13 10]               <- "\r\n"
```

if you concatenate each chunk you get `"at\r\r\n\r\nOK\r\n\r\r\n"` that it's the correct data from the modem.

**Comment by KiddoV** [comment]
@cmaglie  I know you would point the ``\n`` out. But, that line is just a test line of my code. The reason I added ``\n``, because I want to know what is it will print out for each ``index`` of the loop.
This is what I have without the ``\n``:
```txt
[97][116 13 13 10][13][10 79 75 13 10][13][13 10] ...
(Which is correct, but sometime it will be like:)
[116 13 13 10][97][13][10 79 75 13 10][13 10][13]
(Noted the 97-a would jumping around)
``` 
In TeraTerm, it would never happend like that.

**Comment by KiddoV** [comment]
@cmaglie I tested it with a go routine:
```go
go func() {
	for {
		_, err := thisPort.Write([]byte("at" + "\n\r"))
		if err != nil {
			a.LogError(err.Error())
		}
		time.Sleep(time.Millisecond * 10)
	}
}()
```
Which is really fast (10 milliseconds), but, **everything looks as expected**. Weird!
Maybe when using the keyboard to input commands, there will be some delay going on?

**Comment by KiddoV** [comment]
@cmaglie I think I found the problem:
I put the Write() and Read() in the same ``func``, and call it on every command. That's why it is messed up:
```go
func WriteToCom(msg string) {
    _, err := thisPort.Write([]byte(writeMsg + "\n\r"))
	
    buff := make([]byte, 1000)
    for {
	     n, err := thisPort.Read(buff)
	     if err != nil {
	 	    a.LogError("Error reading COM!! " + err.Error())
	     }
	     if n == 0 {
	 	    break
	     }
	     fmt.Print(string(buff[:n]))
    }
}
```
I took the Read() loop out, and put it in a separate routine, everything looks good now.
Thanks for your help anyway!

**Comment by cmaglie** [comment]
> I put the Write() and Read() in the same func, and call it on every command. That's why it is messed up:

You did not show this part... that's why I asked for a **complete** example.

Anyway, glad that you figured it out!

**Comment by KiddoV** [comment]
> You did not show this part... that's why I asked for a **complete** example.

My bad, thank you!
