### ISSUE TITLE
Enumerator panics on windows when removing a device mid enumeration

### ISSUE THREAD

**Issue by advisoft** [bugst/go-serial#138]
panic: runtime error: index out of range [0] with length 0
```
goroutine 883 [running]:\ngo.bug.st/serial/enumerator.retrievePortDetailsFromDevInfo(0xc00011f3b0, 0xc000121560, 0x5, 0x0)
/go/pkg/mod/go.bug.st/serial@v1.3.5/enumerator/usb_windows.go:351 +0x365
go.bug.st/serial/enumerator.nativeGetDetailedPortsList(0x0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/go.bug.st/serial@v1.3.5/enumerator/usb_windows.go:299 +0x1b1
go.bug.st/serial/enumerator.GetDetailedPortsList(...)
/go/pkg/mod/go.bug.st/serial@v1.3.5/enumerator/enumerator.go:31
```
I suspect N needs a zero check on line 350:
![image](https://user-images.githubusercontent.com/11500738/167532184-9918c7a1-495c-4d26-9bdc-fb42034b63ed.png)

**Comment by per1234** [comment]
We have received multiple reports of this panic from users of the [**serial-discovery**](https://github.com/arduino/serial-discovery) tool (via [**Arduino CLI**](https://github.com/arduino/arduino-cli) + [**Arduino IDE**](https://github.com/arduino/arduino-ide)):

- https://forum.arduino.cc/t/no-ports-discovered-of-ide-2-0-0-rc9-rc9-1/1018669/23
- https://forum.arduino.cc/t/no-ports-discovered-of-ide-2-0-0-rc9-rc9-1/1018669/41
- https://forum.arduino.cc/t/no-ports-discovered-of-ide-2-0-0-rc9-rc9-1/1018669/44
