### ISSUE TITLE
Serial.available() value of Arudino is not greater than or equal to 0 when Write() is executed

### ISSUE THREAD

**Issue by syumekino** [bugst/go-serial#171]
I use translation.

Win11 and Arduino UNO, VS code.
When I executed the process of sending a string from PC, Arduino's Serial.read() does not return any value. the return value of Serial.available is also never more than 0.
Read() was executable.
Is there a solution?

**Comment by cmaglie** [comment]
There is a problem in your code I suppose.

But if you don't provide the source code and the sketch you used, nobody can help you.

**Comment by cmaglie** [comment]
Closing for lack of feedback. If you are still interested, please open a new issue and provide more information so I can be able to help you.
