### ISSUE TITLE
Syscall: project file organisation proposal/discussion

### ISSUE THREAD

**Issue by albenik** [bugst/go-serial#21]
So, about https://github.com/albenik/go-serial/commit/68d334cc615660457c9ca6cf114be691727acd04

My motivation is simple. Currently I very active using `go-serial` (thanks!) in my current work. I working with many vending devices, where I have often switch read timeouts while single packet read operation. So I have to implement some new methods peeped in the project https://github.com/pyserial/pyserial (it's only for windows yet, I plans to complete work and propose it to you)

While I learning and comparing both `pyserial` and `go-serial` and looking for simplest way to port code, it was very difficult for me finding syscall definitions scattered throughout the code. Also It was difficult for me to choose a place for new syscalls.
My be if you project fresh for you, and as author you keep in mind design features it's easy. But for me it was difficult. I talks predominantly windows syscalls of course, not for single unix `ioctl`

Therefore I propose to consolidate syscall definitions. There is two way:

1. Put it to one place in `serial_*` files
2. Put it to separated files like in `syscall` package

I choose second way, because I think it's generic apporoach. And it's possible more common for any new people which will want to commit in you prtoject.

**Comment by albenik** [comment]
> I would have accepted the above if the readability gain was substantial, but this doesn't seems the case because, at the moment, the //syscall are near the place where they are effectively used, I think it's a better place that gives more context to understand why those syscall are needed and how they are used. Actually moving them in another file seems to reduce readability IMHO (as well as adding 4 more file to the "mass" of code).

It's true for you — author! Not for me, which have to learn code.
For example:
I look an implementation of some new function in pyserial. I found some syscalls in this implementation. When I read MSDN about found syscalls. When I need to compare exists syscalls in `go-serial` to check all required syscalls present and it look like expected.
With generic approach, I just find a `syscall_*` files and read it.
With consolidated placement approach, I have to do a text search on a project files to find `//sys` entities, when navigate to it and read.
Whith current `go-serial` approach I have to do text search aganin and again to find concrete syscall. Or at leas I have to scroll code up and down, up and down...

**Comment by cmaglie** [comment]
@albenik 
sorry for the long delay, free time is always a scarce resource...

Ok you convinced me, we can go with your suggestions, if you care to push a PR.

Thanks!

**Comment by albenik** [comment]
Pull request ready.

**Comment by cmaglie** [comment]
fixed by #24
