### ISSUE TITLE
trying out the USB enumerator

### ISSUE THREAD

**Issue by jcw** [bugst/go-serial#22]
Hey Cristian,

I'm trying out your new USB code on macOS/64b w/ Go 1.7.5 and get this compiler message:

```
~/G/s/g/s/enumerator (v1|✔) $ go test
# go.bug.st/serial.v1/enumerator
./usb_darwin.go:25: undefined: PortError
./usb_darwin.go:32: undefined: PortError
FAIL	go.bug.st/serial.v1/enumerator [build failed]
```

Anything I can do to get past this hurdle? ("wait" is also fine with me...)

Cheers,
-jcw

**Comment by cmaglie** [comment]
Ooops, I've really missed that!

Fixed by #23
