### ISSUE TITLE
Support for OpenBSD?

### ISSUE THREAD

**Issue by bconway** [bugst/go-serial#27]
Greetings. I previously built a small application in Go for a hardware controller using tarm/serial. It worked well on OS X, but switching to OpenBSD/amd64 made it pretty clear that that wasn't a supported platform (reading stale data, reading unexpected linefeed characters, writes appearing to go missing). My needs are fairly simple, I connect to a "FTDI FT232R USB UART" device, write 2-3 bytes, and read one byte back.

This seemed like the most active Go serial port project, so I figured I'd drop a note. How can I help add OpenBSD support? I skimmed the FreeBSD files, but it was mostly Greek to me. I have plenty of OpenBSD systems to test against, though.

Thanks.

**Comment by cmaglie** [comment]
Fixed by #28
