### ISSUE TITLE
Support non-blocking mode

### ISSUE THREAD

**Issue by Niondir** [bugst/go-serial#31]
I would prefer to set a timeout for reading data instead of blocking till the connection get's closed.

**Comment by albenik** [comment]
here it is https://github.com/albenik/go-serial

**Comment by Niondir** [comment]
Cool thanks, would be nice if it gets ported back into bugst.

**Comment by albenik** [comment]
Yes of course! But it depends on previous improvements (https://github.com/bugst/go-serial/pull/29) which where still not merged here a long-long time.

**Comment by cmaglie** [comment]
Fixed by #109
