### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by MaitreDede** [bugst/go-serial#48]
Hi,
I would like to know if it is possible to add timeouts on read/write operations. Either by setting a timeout value, or a deadline value.
Thanks.

**Comment by LeeSSXX** [comment]
i need fun too

**Comment by lifetyper** [comment]
I give up this package because of lacking read Timeout option

**Comment by MaitreDede** [comment]
Hi @lifetyper what is the package you use as replacement ? Thanks.

**Comment by lifetyper** [comment]
@MaitreDede I use both this package and github.com/tarm/serial for my project,use this for serial port listing only.

**Comment by ygl-rg** [comment]
> @MaitreDede I use both this package and github.com/tarm/serial for my project,use this for serial port listing only.

so am I

**Comment by cbrake** [comment]
if you need timeouts, you may want to consider wrapping the serial port with this package:

https://pkg.go.dev/github.com/simpleiot/simpleiot/respreader?tab=doc

I've been using it for modem control (AT commands), and for RS485 protocols like modbus -- seems to be working well.

**Comment by hb1707** [comment]
> @MaitreDede我将这个软件包和github.com/tarm/serial用于我的项目，仅将此用于串行端口列表。

so do i

> > @MaitreDede I use both this package and github.com/tarm/serial for my project,use this for serial port listing only.
> 
> so am I

+1 so do i
