### ISSUE TITLE
vgo tags?

### ISSUE THREAD

**Issue by silasb** [bugst/go-serial#49]
Any plans to support vgo tags?

**Comment by cmaglie** [comment]
Hi @silasb, honestly I'm a bit out-of-the-loop here... is there a doc that explains what are vgo tags and how to use them?

**Comment by silasb** [comment]
Instead of doing versioning via package names you can now version via a git tag.  I jumped the gun on this GH issue, there is no such  thing as a vgo tag. It's just nicer to work with if there is a git tag. https://research.swtch.com/vgo-tour

**Comment by silasb** [comment]
Yes.

**Comment by cmaglie** [comment]
It seems that also a `go.mod` file is required, I think I'll wait a bit more until a stable release of go tooling to see the best way forward.

**Comment by maddie** [comment]
Currently using `vgo build` in existing project with `go-serial` as dependency will fail with this error:

```
import "go.bug.st/serial.v1": cannot find module providing package go.bug.st/serial.v1
```

If I add the dependency manually to `go.mod` it will fail with below error:

```
go: go.bug.st/serial.v1@v0.0.0-20170728081230-eae1344f9f90: unrecognized import path "go.bug.st/serial.v1" (https fetch: Get https://go.bug.st/serial.v1?go-get=1: net/http: TLS handshake timeout)
```

I guess that's because `vgo` wasn't able to access that URL, but I don't really know how to fix this.

**Comment by silasb** [comment]
I fixed it via: https://github.com/silasb/betaflight-app/blob/master/go.mod

If the repo was tagged with a git version then I think it would be easier
to work with.

—Silas

**Comment by cmaglie** [comment]
`go mod` is now supported with the import `go.bug.st/serial`.
