### ISSUE TITLE
how to get a bluetooth's serail port name?

### ISSUE THREAD

**Issue by naxiemolv** [bugst/go-serial#64]
first thank you for the working of this project, really help me

but I hava question with it.

how to get a bluetooth's serail port name? instead of COMxx 
in mac I get /dev/tty.XXXxxx but in windows i get only COM[1-9]

**Comment by cmaglie** [comment]
COMx is how serial ports are called in Windows...

The only thing that comes to my mind is to look at the USB VID/PID if they match some known bluetooth controllers. I don't know if there is a more general way to detect only bluetooth serial ports.
