### ISSUE TITLE
go.bug.st returning 404

### ISSUE THREAD

**Issue by charles-m-knox** [bugst/go-serial#65]
Hi @cmaglie and all, it appears that go.bug.st is down and I am not able to pull packages. A few colleagues are also seeing 404's when visiting https://go.bug.st. Hopefully this issue helps bring some awareness to it.

Thanks all!

**Comment by cmaglie** [comment]
should be fixed now

(the server is getting old, I'll move to a Cloud VPS in the coming days)

**Comment by charles-m-knox** [comment]
@cmaglie Thank you! It is working now.
