### ISSUE TITLE
go get fails...

### ISSUE THREAD

**Issue by K6TD** [bugst/go-serial#70]
command:
`go get github.com/bugst/go-serial`

Error message:
`package go.bug.st/serial/unixutils: unrecognized import path "go.bug.st/serial/unixutils" (parse https://go.bug.st/serial/unixutils?go-get=1: no go-import meta tags ())
`
go version:
`go version go1.13.1 linux/arm`

**Comment by cmaglie** [comment]
use `go.bug.st/serial`

https://github.com/bugst/go-serial#gomod-transition

**Comment by K6TD** [comment]
please update readme to include:
`go get -u go.bug.st/serial`

Not obvious, at least to me, the correct name to 'get'.

Thanks for the quick response.

KR
