### ISSUE TITLE
How to enbale RTS/CTS handshake?

### ISSUE THREAD

**Issue by sebastian0x62** [bugst/go-serial#95]
Since RTS/CTS handshake is disabled by default, I'm wondering how to enable this feature. Is this supported?

Thank you.

@cmaglie

**Comment by kroppt** [comment]
It looks like you can just call these methods
```go
SetDTR(dtr bool) error
SetRTS(rts bool) error
```
They tell the OS what to do and that's that. So maybe you need to check the Win32 or Linux documentation. Perhaps something you need is missing.
